# Generated by Django 5.2.15 on 2026-06-15 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='Untitled', max_length=256)),
                ('text', models.TextField(blank=True, default='')),
                ('is_public', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, default=None, null=True, unique=True)),
                ('author', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notes',
                'indexes': [models.Index(fields=['author', '-updated_at'], name='notes_author_updated_idx')],
            },
        ),
    ]
